name: 'setup-node'
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Setup Environment with mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
      with:
        cache: false

    - name: Cache node modules
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
