name: 'setup-node'
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Setup Environment with mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      with:
        cache: false

    - name: Cache node modules
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
