name: 'setup-node'
description: 'setup node'

runs:
  using: 'composite'
  steps:
    - name: Setup Environment with mise
      uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3
      with:
        cache: false

    - name: Cache node modules
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
