// eslint-disable-next-line import/no-relative-packages
import A11lintPlaywright from '../../src/index';
import { test } from './AccessibilityFixtures';

test('Accessibility testing ', async ({ page, URLS }) => {
  const a11ylint = new A11lintPlaywright();
  await a11ylint.analyze({
    options: {
      html: true,
      json: true,
      cli: false, // Set to true if you want to generate CLI output
    },
    page,
    urls: URLS,
  });

  // await (async () => {
  //   await page.setContent(pdfs);
  //   await page.pdf({
  //     path: `./tests/${baseUrl.replace(/https?:\/\//, "")}.pdf`,
  //     format: "A4",
  //     displayHeaderFooter: true,
  //     headerTemplate:
  //       '<span style="font-size:10px;  margin-left: 20px;">a11ylint autogenerated report</span>',
  //     footerTemplate:
  //       '<span style="font-size:10px; margin-left: 20px;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>',
  //     margin: { top: "50px", bottom: "50px", left: "20px", right: "20px" },
  //     printBackground: true,
  //   });
  // })();
});
